FROM python:3.10-slim
# stable python version

WORKDIR /app
# work dir

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*
# system dependencies can be seprated (packed together to reduce image layers)

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir gunicorn

COPY . .


EXPOSE 8000

CMD ["gunicorn", "statuspage.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "2"]