apiVersion: v1
kind: Secret
metadata:
  name: statuspage-secrets
  namespace: statuspage
type: Opaque
stringData:
  DB_PASSWORD: "statuspage"
  POSTGRES_PASSWORD: "statuspage"
  SECRET_KEY: "change-me-to-a-long-random-string"
  SUPERUSER_NAME: "admin"
  SUPERUSER_EMAIL: "admin@example.com"
  SUPERUSER_PASSWORD: "admin"
