apiVersion: v1
kind: Service
metadata:
  name: statuspage-svc
  namespace: statuspage
  labels:
    workload: StatusPage-ui
spec:
  selector:
    workload: StatusPage-ui
  ports:
    - port: 80
      targetPort: 8000
      name: http
