grafana:
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: true
prometheus:
  prometheusSpec:
    # This instructs Prometheus to look in ALL namespaces
    podMonitorNamespaceSelector: {}
    serviceMonitorNamespaceSelector: {}
    ruleNamespaceSelector: {}
